#ifndef CSR_KEYBOARD_KEYS_H
#define CSR_KEYBOARD_KEYS_H

#include "../PlatformDefines.h"

typedef enum
{
#ifdef CSR_PLATFORM_WIN
	csrKeyA = 65,            
	csrKeyB,            
	csrKeyC,            
	csrKeyD,            
	csrKeyE,            
	csrKeyF,            
	csrKeyG,            
	csrKeyH,            
	csrKeyI,            
	csrKeyJ,            
	csrKeyK,            
	csrKeyL,            
	csrKeyM,            
	csrKeyN,            
	csrKeyO,            
	csrKeyP,            
	csrKeyQ,            
	csrKeyR,            
	csrKeyS,            
	csrKeyT,            
	csrKeyU,            
	csrKeyV,            
	csrKeyW,            
	csrKeyX,            
	csrKeyY,            
	csrKeyZ,            
	csrKeyNum0 = 30,         
	csrKeyNum1,         
	csrKeyNum2,         
	csrKeyNum3,         
	csrKeyNum4,         
	csrKeyNum5,         
	csrKeyNum6,         
	csrKeyNum7,         
	csrKeyNum8,         
	csrKeyNum9,         
	csrKeyEscape = 0x1B,
	csrKeyControlLeft = 0xA2,
	csrKeyShiftLeft = 0xA0,
	csrKeyAltLeft = 0x12,
	csrKeyMenuLeft = 0xA4,     
	csrKeyControlRight = 0xA3,
	csrKeyShiftRight = 0xA1,
	csrKeyAltRight = 0x12,
	csrKeyMenuRight = 0xA5,
	csrKeyBracketLeft = 0xDB,
	csrKeyBracketRight = 0xDD,
	csrKeyColon = 0xDE,
	csrKeyComma = 0xBC,
	csrKeyPeriod = 0xBE,
	csrKeyQuote = 0xDE,
	csrKeySlash = 0xBF,
	csrKeyBackslash = 0xDC,
	csrKeyTilde = 0xC0,
	csrKeyEqual = 0xBB,
	csrKeyDash = 0xBD,
	csrKeySpace = 0x20,
	csrKeyReturn = 0x0D,
	csrKeyBack = 0x08,
	csrKeyTab = 0x09,
	csrKeyPageup = 0x21,
	csrKeyPagedown = 0x22,
	csrKeyEnd = 0x23,
	csrKeyHome = 0x24,
	csrKeyInsert = 0x2D,
	csrKeyDelete = 0x2E,
	csrKeyAdd = 0xBB,
	csrKeySub = 0xBD,
	csrKeyMul = 0x6A,
	csrKeyDiv = 0x6F,
	csrKeyLeft = 0x25,
	csrKeyRight = 0x27,
	csrKeyUp = 0x26,
	csrKeyDown = 0x28,
	csrKeyNumpad0 = 96,      
	csrKeyNumpad1,
	csrKeyNumpad2,
	csrKeyNumpad3,
	csrKeyNumpad4,
	csrKeyNumpad5,
	csrKeyNumpad6,
	csrKeyNumpad7,
	csrKeyNumpad8,
	csrKeyNumpad9,
	csrKeyF1 = 112,           
	csrKeyF2 ,      
	csrKeyF3 ,      
	csrKeyF4 ,      
	csrKeyF5 ,      
	csrKeyF6 ,      
	csrKeyF7 ,      
	csrKeyF8 ,      
	csrKeyF9 ,      
	csrKeyF10 ,       
	csrKeyF11 ,       
	csrKeyF12 ,       
	csrKeyF13 ,       
	csrKeyF14 ,       
	csrKeyF15 ,       
	csrKeyPause = 0x13
#endif
} KeyboardKeys;


#endif //CSR_KEYBOARD_KEYS_H