#ifndef CSR_KEYBOARD_KEYS_H
#define CSR_KEYBOARD_KEYS_H

#include <SFML/Window.h>

typedef enum
{
	csrKeyA = sfKeyA,            
	csrKeyB = sfKeyB,            
	csrKeyC = sfKeyC,            
	csrKeyD = sfKeyD,            
	csrKeyE = sfKeyE,            
	csrKeyF = sfKeyF,            
	csrKeyG = sfKeyG,            
	csrKeyH = sfKeyH,            
	csrKeyI = sfKeyI,            
	csrKeyJ = sfKeyJ,            
	csrKeyK = sfKeyK,            
	csrKeyL = sfKeyL,            
	csrKeyM = sfKeyM,            
	csrKeyN = sfKeyN,            
	csrKeyO = sfKeyO,            
	csrKeyP = sfKeyP,            
	csrKeyQ = sfKeyQ,            
	csrKeyR = sfKeyR,            
	csrKeyS = sfKeyS,            
	csrKeyT = sfKeyT,            
	csrKeyU = sfKeyU,            
	csrKeyV = sfKeyV,            
	csrKeyW = sfKeyW,            
	csrKeyX = sfKeyX,            
	csrKeyY = sfKeyY,            
	csrKeyZ = sfKeyZ,            
	csrKeyNum0 = sfKeyNum0,         
	csrKeyNum1 = sfKeyNum1,         
	csrKeyNum2 = sfKeyNum2,         
	csrKeyNum3 = sfKeyNum3,         
	csrKeyNum4 = sfKeyNum4,         
	csrKeyNum5 = sfKeyNum5,         
	csrKeyNum6 = sfKeyNum6,         
	csrKeyNum7 = sfKeyNum7,         
	csrKeyNum8 = sfKeyNum8,         
	csrKeyNum9 = sfKeyNum9,         
	csrKeyEscape = sfKeyEscape,       
	csrKeyControlLeft = sfKeyLControl,     
	csrKeyShiftLeft = sfKeyLShift,       
	csrKeyAltLeft = sfKeyLAlt,         
	csrKeySystemLeft = sfKeyLSystem,     
	csrKeyControlRight = sfKeyRControl,     
	csrKeyShiftRight = sfKeyRShift,       
	csrKeyAltRight = sfKeyRAlt,         
	csrKeySystemRight = sfKeyRSystem,      
	csrKeyKeyMenu = sfKeyMenu,         
	csrKeyBracketLeft = sfKeyLBracket,     
	csrKeyBracketRight = sfKeyRBracket,     
	csrKeyColon = sfKeySemiColon,    
	csrKeyComma = sfKeyComma,        
	csrKeyPeriod = sfKeyPeriod,       
	csrKeyQuote = sfKeyQuote,        
	csrKeySlash = sfKeySlash,        
	csrKeyBackslash = sfKeyBackSlash,    
	csrKeyTilde = sfKeyTilde,        
	csrKeyEqual = sfKeyEqual,        
	csrKeyDash = sfKeyDash,         
	csrKeySpace = sfKeySpace,        
	csrKeyReturn = sfKeyReturn,       
	csrKeyBack = sfKeyBack,         
	csrKeyTab = sfKeyTab,          
	csrKeyPageup = sfKeyPageUp,       
	csrKeyPagedown = sfKeyPageDown,     
	csrKeyEnd = sfKeyEnd,          
	csrKeyHome = sfKeyHome,         
	csrKeyInsert = sfKeyInsert,       
	csrKeyDelete = sfKeyDelete,       
	csrKeyAdd = sfKeyAdd,          
	csrKeySub = sfKeySubtract,     
	csrKeyMul = sfKeyMultiply,     
	csrKeyDiv = sfKeyDivide,       
	csrKeyLeft = sfKeyLeft,         
	csrKeyRight = sfKeyRight,        
	csrKeyUp = sfKeyUp,           
	csrKeyDown = sfKeyDown,         
	csrKeyNumpad0 = sfKeyNumpad0,      
	csrKeyNumpad1 = sfKeyNumpad1,      
	csrKeyNumpad2 = sfKeyNumpad2,      
	csrKeyNumpad3 = sfKeyNumpad3,      
	csrKeyNumpad4 = sfKeyNumpad4,      
	csrKeyNumpad5 = sfKeyNumpad5,      
	csrKeyNumpad6 = sfKeyNumpad6,      
	csrKeyNumpad7 = sfKeyNumpad7,      
	csrKeyNumpad8 = sfKeyNumpad8,      
	csrKeyNumpad9 = sfKeyNumpad9,      
	csrKeyF1 = sfKeyF1,           
	csrKeyF2 = sfKeyF2,           
	csrKeyF3 = sfKeyF3,           
	csrKeyF4 = sfKeyF4,           
	csrKeyF5 = sfKeyF5,           
	csrKeyF6 = sfKeyF6,           
	csrKeyF7 = sfKeyF7,           
	csrKeyF8 = sfKeyF8,           
	csrKeyF9 = sfKeyF9,           
	csrKeyF10 = sfKeyF10,          
	csrKeyF11 = sfKeyF11,          
	csrKeyF12 = sfKeyF12,          
	csrKeyF13 = sfKeyF13,          
	csrKeyF14 = sfKeyF14,          
	csrKeyF15 = sfKeyF15,          
	csrKeyPause = sfKeyPause	
} KeyboardKeys;


#endif //CSR_KEYBOARD_KEYS_H